Repository WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P2-Team3, pull requests merged in 2024-04, with the labels that each got.

#1 Clear App.jsx
  client/src/App.css
  client/src/App.jsx
Labels: CORRECTIONS DONE, REVIEWED

#2 Header
  client/src/App.css
  client/src/App.jsx
  client/src/components/Header.jsx
Labels: REVIEWED

#7 Canva
  client/package.json
  client/src/App.jsx
  client/src/components/Canva.jsx
Labels: REVIEWED

#6 Add card
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/Terra.png
  client/src/components/Card.jsx
Labels: CORRECTIONS DONE

#36 création de la premiére section de la home page avec un peu de css
  client/src/App.css
  client/src/components/Main.jsx
  client/src/components/Section1.jsx
  client/src/pages/Home.jsx
Labels: REVIEWED

#44 mise en orbit
  client/src/components/Canva.jsx
Labels: REVIEW REQUESTED

#47 Creation d'un fichier data qui va contenir les description des corps …
  client/src/components/Card.jsx
  client/src/data/data.js
  client/src/pages/Map.jsx
Labels: REVIEW REQUESTED

#46 Scene
  client/src/assets/images/spaceDN.jpg
  client/src/assets/images/spaceUP.jpg
  client/src/assets/images/spacebk.jpg
  client/src/assets/images/spaceft.jpg
  client/src/assets/images/spacelf.jpg
  client/src/assets/images/spacert.jpg
  client/src/components/Canva.jsx
Labels: CONFLICTS RESOLVED

#49 add card in, canva
  client/src/App.scss
  client/src/components/Canva.jsx
  client/src/components/Card.jsx
  client/src/pages/Map.jsx
Labels: REVIEWED

#51 home_planets
  client/src/App.scss
  client/src/assets/bgMain/jupiterInfo.jpg
  client/src/assets/bgMain/marsInfo.jpg
  client/src/assets/bgMain/mercureInfo.jpg
  client/src/assets/bgMain/neptuneInfo.jpg
  client/src/assets/bgMain/saturnInfo.jpg
  client/src/assets/bgMain/terreInfo.jpg
  client/src/assets/bgMain/uranusInfo.jpg
  client/src/assets/bgMain/venusInfo.jpg
  client/src/components/Canva.jsx
  client/src/components/PlanetInfo.jsx
  client/src/pages/Home.jsx
Labels: CONFLICTS RESOLVED, REVIEWED

#55 intégration api dans la card
  client/src/components/Canva.jsx
  client/src/components/Card.jsx
Labels: REVIEW REQUESTED

#56 post-prod + light ajouté
  client/src/components/Canva.jsx
Labels: REVIEW REQUESTED

#57 add click planets
  client/src/components/Canva.jsx
Labels: REVIEW REQUESTED

#58 Add circle
  client/src/components/Canva.jsx
Labels: REVIEW REQUESTED

#68 Modifimpfooter
  client/src/components/Footer.jsx
Labels: REVIEW REQUESTED

#72 Rotation p/s
  client/src/App.scss
  client/src/components/Canva.jsx
  client/src/components/Card.jsx
Labels: REVIEW REQUESTED, REVIEWED

#78 Elementstars
  client/src/assets/bgMain/soleil.jpg
  client/src/components/Canva.jsx
  client/src/components/Card.jsx
Labels: REVIEW REQUESTED, REVIEWED

#76 image in card
  client/src/assets/bgMain/soleil.jpg
  client/src/components/Card.jsx
Labels: REVIEWED

#80 scroll to link to map
  client/src/components/PlanetInfo.jsx
  client/src/components/Section2.jsx
  client/src/pages/Map.jsx
Labels: REVIEW REQUESTED

#85 je centre l'audio pour la 17 fois
  client/src/App.scss
Labels: REVIEWED

#81 Audio style
  client/index.html
  client/package.json
  client/src/App.jsx
  client/src/components/AudioPlayer.jsx
  client/src/components/Nav.jsx
  client/src/components/PlanetInfo.jsx
  client/src/data/track.js
Labels: REVIEWED

#87 fix anneaux de saturne
  client/src/components/Canva.jsx
Labels: REVIEW REQUESTED, REVIEWED

#89 New Component MenuBar
  client/src/App.scss
  client/src/components/CosmoHub.jsx
  client/src/components/MenuBar.jsx
Labels: CONFLICTS RESOLVED

#91 fix new size
  client/src/components/Canva.jsx
Labels: REVIEW REQUESTED

#92 fixcss
  client/src/App.scss
  client/src/components/Canva.jsx
  client/src/components/Card.jsx
  client/src/components/MenuBar.jsx
  client/src/pages/Map.jsx
Labels: REVIEW REQUESTED

#97 readme
  README.md
Labels: REVIEW REQUESTED

#98 la musique ne se reset pas entre chaque page
  client/src/App.jsx
  client/src/pages/CosmoHub.jsx
  client/src/pages/Home.jsx
  client/src/pages/Map.jsx
Labels: REVIEW REQUESTED

#99 Update README.md
  README.md
Labels: REVIEW REQUESTED

#102 Update README.md
  README.md
Labels: REVIEW REQUESTED

#105 Add Responsive
  client/src/App.scss
Labels: REVIEW REQUESTED

#106 fixcss
  client/src/App.scss
Labels: REVIEW REQUESTED

#107 keyframe float card
  client/src/App.scss
Labels: REVIEW REQUESTED

#108 fixcss cursor pointer page cosmo hub
  client/src/App.scss
Labels: REVIEW REQUESTED

#110 fixcss cursor pointer page cosmo hub
  client/src/App.scss
Labels: REVIEW REQUESTED

#109 scrolto withy good adress
  client/src/pages/Map.jsx
Labels: REVIEW REQUESTED

#111 Add
  client/src/assets/images/Cosmo.jpg
  client/src/assets/images/message.png
  client/src/components/Canva.jsx
Labels: REVIEW REQUESTED

#113 fixcorrect title in html
  client/index.html
Labels: REVIEW REQUESTED
